environment: stg
deployment:
  replicas: 2
  appendEnv:
    - name: PORT
      value: "30124"
    - name: ETCD
      value: "http://etcd.staging-ads.applifier.info:4001"
ingress:
  secretName: tls-wildcard-staging-unityads-unity3d-com
  host: ccentral.staging.unityads.unity3d.com
